{
    "device": "cuda",
    "epochs": 100,
    "batch_size": 1,
    "lr": 0.001,
    "shape_dir": "../../../datasets/shrec_r",
    "k": 128,
    "model": {
        "class": "CaoNet",
        "params": {
            "descriptor": {
                "type": "diffusion_net",
                "params": {
                    "out_channels" : 128,
                    "cache_dir" : "../../../datasets/shrec_r/diffusion/"
                }
            },
            "forward_map": {
                "lmbda": 0.001,
                "resolvent_gamma": 1
            }
        }
    },
    "loss_config": {
        "Orthonormality": 1.0,
        "Laplacian_Commutativity": 0.01,
        "Fmap_Supervision": 1.0
    },
    "save_interval": 50
}