name: "Tests"

on:
  push:
    # TODO: add paths or paths-ignore
    branches: [main, github-actions-test]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Build using Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{matrix.os}}-${{matrix.python-version}}-${{hashFiles('pyproject.toml')}}

      - name: Setting up rust
        run: rustup default nightly

      - name: Installing dependencies [pip]
        run: |
          pip install --upgrade pip
          pip install pytest-cov
          pip install -e .[test]

      - name: Adding annotations [pytest]
        run: pip install pytest-github-actions-annotate-failures

      - name: Unit testing [pytest]
        run: |
          pytest --cov-report term tests
